services:
  - type: web
    name: calorie-counter
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn calorie_tracker_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - fromDatabase:
          name: calorie-tracker-db
          property: connectionString
        key: DATABASE_URL

databases:
  - name: calorie-tracker-db
    plan: free