services:
  - type: web
    name: calorie-counter
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn calorie_tracker_project.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DB_NAME
        fromDatabase:
          name: calorie-tracker-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: calorie-tracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: calorie-tracker-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: calorie-tracker-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: calorie-tracker-db
          property: port

databases:
  - name: calorie-tracker-db
    plan: free